/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Authors;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorsRecord extends TableRecordImpl<AuthorsRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -374747590;

    /**
     * Setter for <code>public.AUTHORS.ID</code>.
     */
    public AuthorsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.AUTHORS.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.AUTHORS.FIRSNAME</code>.
     */
    public AuthorsRecord setFirsname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.AUTHORS.FIRSNAME</code>.
     */
    public String getFirsname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.AUTHORS.SECONDNAME</code>.
     */
    public AuthorsRecord setSecondname(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.AUTHORS.SECONDNAME</code>.
     */
    public String getSecondname() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Authors.AUTHORS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Authors.AUTHORS.FIRSNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Authors.AUTHORS.SECONDNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFirsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getSecondname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFirsname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getSecondname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorsRecord value2(String value) {
        setFirsname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorsRecord value3(String value) {
        setSecondname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthorsRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthorsRecord
     */
    public AuthorsRecord() {
        super(Authors.AUTHORS);
    }

    /**
     * Create a detached, initialised AuthorsRecord
     */
    public AuthorsRecord(Integer id, String firsname, String secondname) {
        super(Authors.AUTHORS);

        set(0, id);
        set(1, firsname);
        set(2, secondname);
    }
}
