/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Organizations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizationsRecord extends TableRecordImpl<OrganizationsRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 2132185734;

    /**
     * Setter for <code>public.organizations.organization</code>.
     */
    public OrganizationsRecord setOrganization(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.organizations.organization</code>.
     */
    public String getOrganization() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.organizations.inn</code>.
     */
    public OrganizationsRecord setInn(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.organizations.inn</code>.
     */
    public String getInn() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.organizations.checkingaccount</code>.
     */
    public OrganizationsRecord setCheckingaccount(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.organizations.checkingaccount</code>.
     */
    public String getCheckingaccount() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Organizations.ORGANIZATIONS.ORGANIZATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Organizations.ORGANIZATIONS.INN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Organizations.ORGANIZATIONS.CHECKINGACCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCheckingaccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getInn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCheckingaccount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value1(String value) {
        setOrganization(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value2(String value) {
        setInn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord value3(String value) {
        setCheckingaccount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrganizationsRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrganizationsRecord
     */
    public OrganizationsRecord() {
        super(Organizations.ORGANIZATIONS);
    }

    /**
     * Create a detached, initialised OrganizationsRecord
     */
    public OrganizationsRecord(String organization, String inn, String checkingaccount) {
        super(Organizations.ORGANIZATIONS);

        set(0, organization);
        set(1, inn);
        set(2, checkingaccount);
    }
}
