/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybillposition;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillpositionRecord extends UpdatableRecordImpl<WaybillpositionRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -164568095;

    /**
     * Setter for <code>public.waybillposition.waybillsid</code>.
     */
    public WaybillpositionRecord setWaybillsid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillposition.waybillsid</code>.
     */
    public Integer getWaybillsid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.waybillposition.price</code>.
     */
    public WaybillpositionRecord setPrice(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillposition.price</code>.
     */
    public Integer getPrice() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.waybillposition.nomenclature</code>.
     */
    public WaybillpositionRecord setNomenclature(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillposition.nomenclature</code>.
     */
    public String getNomenclature() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.waybillposition.quantity</code>.
     */
    public WaybillpositionRecord setQuantity(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.waybillposition.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Waybillposition.WAYBILLPOSITION.WAYBILLSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Waybillposition.WAYBILLPOSITION.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Waybillposition.WAYBILLPOSITION.NOMENCLATURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Waybillposition.WAYBILLPOSITION.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWaybillsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getNomenclature();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWaybillsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getNomenclature();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionRecord value1(Integer value) {
        setWaybillsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionRecord value2(Integer value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionRecord value3(String value) {
        setNomenclature(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionRecord value4(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillpositionRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillpositionRecord
     */
    public WaybillpositionRecord() {
        super(Waybillposition.WAYBILLPOSITION);
    }

    /**
     * Create a detached, initialised WaybillpositionRecord
     */
    public WaybillpositionRecord(Integer waybillsid, Integer price, String nomenclature, Integer quantity) {
        super(Waybillposition.WAYBILLPOSITION);

        set(0, waybillsid);
        set(1, price);
        set(2, nomenclature);
        set(3, quantity);
    }
}
