/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.Waybills;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WaybillsRecord extends UpdatableRecordImpl<WaybillsRecord> implements Record3<Integer, Date, String> {

    private static final long serialVersionUID = 1438654557;

    /**
     * Setter for <code>public.waybills.waybillsid</code>.
     */
    public WaybillsRecord setWaybillsid(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.waybills.waybillsid</code>.
     */
    public Integer getWaybillsid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.waybills.waybilldate</code>.
     */
    public WaybillsRecord setWaybilldate(Date value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.waybills.waybilldate</code>.
     */
    public Date getWaybilldate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>public.waybills.organization</code>.
     */
    public WaybillsRecord setOrganization(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.waybills.organization</code>.
     */
    public String getOrganization() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Date, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Date, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Waybills.WAYBILLS.WAYBILLSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Waybills.WAYBILLS.WAYBILLDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Waybills.WAYBILLS.ORGANIZATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWaybillsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getWaybilldate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWaybillsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getWaybilldate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOrganization();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord value1(Integer value) {
        setWaybillsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord value2(Date value) {
        setWaybilldate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord value3(String value) {
        setOrganization(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WaybillsRecord values(Integer value1, Date value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WaybillsRecord
     */
    public WaybillsRecord() {
        super(Waybills.WAYBILLS);
    }

    /**
     * Create a detached, initialised WaybillsRecord
     */
    public WaybillsRecord(Integer waybillsid, Date waybilldate, String organization) {
        super(Waybills.WAYBILLS);

        set(0, waybillsid);
        set(1, waybilldate);
        set(2, organization);
    }
}
