/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authors implements Serializable {

    private static final long serialVersionUID = 35766899;

    private final Integer id;
    private final String  firsname;
    private final String  secondname;

    public Authors(Authors value) {
        this.id = value.id;
        this.firsname = value.firsname;
        this.secondname = value.secondname;
    }

    public Authors(
        Integer id,
        String  firsname,
        String  secondname
    ) {
        this.id = id;
        this.firsname = firsname;
        this.secondname = secondname;
    }

    public Integer getId() {
        return this.id;
    }

    public String getFirsname() {
        return this.firsname;
    }

    public String getSecondname() {
        return this.secondname;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authors (");

        sb.append(id);
        sb.append(", ").append(firsname);
        sb.append(", ").append(secondname);

        sb.append(")");
        return sb.toString();
    }
}
