/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizations implements Serializable {

    private static final long serialVersionUID = 1919626554;

    private final String organization;
    private final String inn;
    private final String checkingaccount;

    public Organizations(Organizations value) {
        this.organization = value.organization;
        this.inn = value.inn;
        this.checkingaccount = value.checkingaccount;
    }

    public Organizations(
        String organization,
        String inn,
        String checkingaccount
    ) {
        this.organization = organization;
        this.inn = inn;
        this.checkingaccount = checkingaccount;
    }

    public String getOrganization() {
        return this.organization;
    }

    public String getInn() {
        return this.inn;
    }

    public String getCheckingaccount() {
        return this.checkingaccount;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organizations (");

        sb.append(organization);
        sb.append(", ").append(inn);
        sb.append(", ").append(checkingaccount);

        sb.append(")");
        return sb.toString();
    }
}
