/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybillposition implements Serializable {

    private static final long serialVersionUID = -1816811535;

    private final Integer waybillsid;
    private final Integer price;
    private final String  nomenclature;
    private final Integer quantity;

    public Waybillposition(Waybillposition value) {
        this.waybillsid = value.waybillsid;
        this.price = value.price;
        this.nomenclature = value.nomenclature;
        this.quantity = value.quantity;
    }

    public Waybillposition(
        Integer waybillsid,
        Integer price,
        String  nomenclature,
        Integer quantity
    ) {
        this.waybillsid = waybillsid;
        this.price = price;
        this.nomenclature = nomenclature;
        this.quantity = quantity;
    }

    public Integer getWaybillsid() {
        return this.waybillsid;
    }

    public Integer getPrice() {
        return this.price;
    }

    public String getNomenclature() {
        return this.nomenclature;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Waybillposition (");

        sb.append(waybillsid);
        sb.append(", ").append(price);
        sb.append(", ").append(nomenclature);
        sb.append(", ").append(quantity);

        sb.append(")");
        return sb.toString();
    }
}
