/*
 * This file is generated by jOOQ.
 */
package db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waybills implements Serializable {

    private static final long serialVersionUID = 1957352917;

    private final Integer waybillsid;
    private final Date    waybilldate;
    private final String  organization;

    public Waybills(Waybills value) {
        this.waybillsid = value.waybillsid;
        this.waybilldate = value.waybilldate;
        this.organization = value.organization;
    }

    public Waybills(
        Integer waybillsid,
        Date    waybilldate,
        String  organization
    ) {
        this.waybillsid = waybillsid;
        this.waybilldate = waybilldate;
        this.organization = organization;
    }

    public Integer getWaybillsid() {
        return this.waybillsid;
    }

    public Date getWaybilldate() {
        return this.waybilldate;
    }

    public String getOrganization() {
        return this.organization;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Waybills (");

        sb.append(waybillsid);
        sb.append(", ").append(waybilldate);
        sb.append(", ").append(organization);

        sb.append(")");
        return sb.toString();
    }
}
