/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.gradle.db.information_schema;


import javax.annotation.Generated;

import org.jooq.example.gradle.db.information_schema.tables.Catalogs;
import org.jooq.example.gradle.db.information_schema.tables.Collations;
import org.jooq.example.gradle.db.information_schema.tables.ColumnPrivileges;
import org.jooq.example.gradle.db.information_schema.tables.Columns;
import org.jooq.example.gradle.db.information_schema.tables.Constants;
import org.jooq.example.gradle.db.information_schema.tables.Constraints;
import org.jooq.example.gradle.db.information_schema.tables.CrossReferences;
import org.jooq.example.gradle.db.information_schema.tables.Domains;
import org.jooq.example.gradle.db.information_schema.tables.FunctionAliases;
import org.jooq.example.gradle.db.information_schema.tables.FunctionColumns;
import org.jooq.example.gradle.db.information_schema.tables.Help;
import org.jooq.example.gradle.db.information_schema.tables.InDoubt;
import org.jooq.example.gradle.db.information_schema.tables.Indexes;
import org.jooq.example.gradle.db.information_schema.tables.Locks;
import org.jooq.example.gradle.db.information_schema.tables.QueryStatistics;
import org.jooq.example.gradle.db.information_schema.tables.Rights;
import org.jooq.example.gradle.db.information_schema.tables.Roles;
import org.jooq.example.gradle.db.information_schema.tables.Schemata;
import org.jooq.example.gradle.db.information_schema.tables.Sequences;
import org.jooq.example.gradle.db.information_schema.tables.SessionState;
import org.jooq.example.gradle.db.information_schema.tables.Sessions;
import org.jooq.example.gradle.db.information_schema.tables.Settings;
import org.jooq.example.gradle.db.information_schema.tables.TablePrivileges;
import org.jooq.example.gradle.db.information_schema.tables.TableTypes;
import org.jooq.example.gradle.db.information_schema.tables.Triggers;
import org.jooq.example.gradle.db.information_schema.tables.TypeInfo;
import org.jooq.example.gradle.db.information_schema.tables.Users;
import org.jooq.example.gradle.db.information_schema.tables.Views;


/**
 * Convenience access to all tables in INFORMATION_SCHEMA
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>INFORMATION_SCHEMA.CATALOGS</code>.
     */
    public static final Catalogs CATALOGS = org.jooq.example.gradle.db.information_schema.tables.Catalogs.CATALOGS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLLATIONS</code>.
     */
    public static final Collations COLLATIONS = org.jooq.example.gradle.db.information_schema.tables.Collations.COLLATIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMNS</code>.
     */
    public static final Columns COLUMNS = org.jooq.example.gradle.db.information_schema.tables.Columns.COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.COLUMN_PRIVILEGES</code>.
     */
    public static final ColumnPrivileges COLUMN_PRIVILEGES = org.jooq.example.gradle.db.information_schema.tables.ColumnPrivileges.COLUMN_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTANTS</code>.
     */
    public static final Constants CONSTANTS = org.jooq.example.gradle.db.information_schema.tables.Constants.CONSTANTS;

    /**
     * The table <code>INFORMATION_SCHEMA.CONSTRAINTS</code>.
     */
    public static final Constraints CONSTRAINTS = org.jooq.example.gradle.db.information_schema.tables.Constraints.CONSTRAINTS;

    /**
     * The table <code>INFORMATION_SCHEMA.CROSS_REFERENCES</code>.
     */
    public static final CrossReferences CROSS_REFERENCES = org.jooq.example.gradle.db.information_schema.tables.CrossReferences.CROSS_REFERENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.DOMAINS</code>.
     */
    public static final Domains DOMAINS = org.jooq.example.gradle.db.information_schema.tables.Domains.DOMAINS;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_ALIASES</code>.
     */
    public static final FunctionAliases FUNCTION_ALIASES = org.jooq.example.gradle.db.information_schema.tables.FunctionAliases.FUNCTION_ALIASES;

    /**
     * The table <code>INFORMATION_SCHEMA.FUNCTION_COLUMNS</code>.
     */
    public static final FunctionColumns FUNCTION_COLUMNS = org.jooq.example.gradle.db.information_schema.tables.FunctionColumns.FUNCTION_COLUMNS;

    /**
     * The table <code>INFORMATION_SCHEMA.HELP</code>.
     */
    public static final Help HELP = org.jooq.example.gradle.db.information_schema.tables.Help.HELP;

    /**
     * The table <code>INFORMATION_SCHEMA.INDEXES</code>.
     */
    public static final Indexes INDEXES = org.jooq.example.gradle.db.information_schema.tables.Indexes.INDEXES;

    /**
     * The table <code>INFORMATION_SCHEMA.IN_DOUBT</code>.
     */
    public static final InDoubt IN_DOUBT = org.jooq.example.gradle.db.information_schema.tables.InDoubt.IN_DOUBT;

    /**
     * The table <code>INFORMATION_SCHEMA.LOCKS</code>.
     */
    public static final Locks LOCKS = org.jooq.example.gradle.db.information_schema.tables.Locks.LOCKS;

    /**
     * The table <code>INFORMATION_SCHEMA.QUERY_STATISTICS</code>.
     */
    public static final QueryStatistics QUERY_STATISTICS = org.jooq.example.gradle.db.information_schema.tables.QueryStatistics.QUERY_STATISTICS;

    /**
     * The table <code>INFORMATION_SCHEMA.RIGHTS</code>.
     */
    public static final Rights RIGHTS = org.jooq.example.gradle.db.information_schema.tables.Rights.RIGHTS;

    /**
     * The table <code>INFORMATION_SCHEMA.ROLES</code>.
     */
    public static final Roles ROLES = org.jooq.example.gradle.db.information_schema.tables.Roles.ROLES;

    /**
     * The table <code>INFORMATION_SCHEMA.SCHEMATA</code>.
     */
    public static final Schemata SCHEMATA = org.jooq.example.gradle.db.information_schema.tables.Schemata.SCHEMATA;

    /**
     * The table <code>INFORMATION_SCHEMA.SEQUENCES</code>.
     */
    public static final Sequences SEQUENCES = org.jooq.example.gradle.db.information_schema.tables.Sequences.SEQUENCES;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSIONS</code>.
     */
    public static final Sessions SESSIONS = org.jooq.example.gradle.db.information_schema.tables.Sessions.SESSIONS;

    /**
     * The table <code>INFORMATION_SCHEMA.SESSION_STATE</code>.
     */
    public static final SessionState SESSION_STATE = org.jooq.example.gradle.db.information_schema.tables.SessionState.SESSION_STATE;

    /**
     * The table <code>INFORMATION_SCHEMA.SETTINGS</code>.
     */
    public static final Settings SETTINGS = org.jooq.example.gradle.db.information_schema.tables.Settings.SETTINGS;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLES</code>.
     */
    public static final org.jooq.example.gradle.db.information_schema.tables.Tables TABLES = org.jooq.example.gradle.db.information_schema.tables.Tables.TABLES;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_PRIVILEGES</code>.
     */
    public static final TablePrivileges TABLE_PRIVILEGES = org.jooq.example.gradle.db.information_schema.tables.TablePrivileges.TABLE_PRIVILEGES;

    /**
     * The table <code>INFORMATION_SCHEMA.TABLE_TYPES</code>.
     */
    public static final TableTypes TABLE_TYPES = org.jooq.example.gradle.db.information_schema.tables.TableTypes.TABLE_TYPES;

    /**
     * The table <code>INFORMATION_SCHEMA.TRIGGERS</code>.
     */
    public static final Triggers TRIGGERS = org.jooq.example.gradle.db.information_schema.tables.Triggers.TRIGGERS;

    /**
     * The table <code>INFORMATION_SCHEMA.TYPE_INFO</code>.
     */
    public static final TypeInfo TYPE_INFO = org.jooq.example.gradle.db.information_schema.tables.TypeInfo.TYPE_INFO;

    /**
     * The table <code>INFORMATION_SCHEMA.USERS</code>.
     */
    public static final Users USERS = org.jooq.example.gradle.db.information_schema.tables.Users.USERS;

    /**
     * The table <code>INFORMATION_SCHEMA.VIEWS</code>.
     */
    public static final Views VIEWS = org.jooq.example.gradle.db.information_schema.tables.Views.VIEWS;
}
