/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Waybillposition;
import db.tables.Waybills;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index WAYBILLPOSITION_PKEY = Indexes0.WAYBILLPOSITION_PKEY;
    public static final Index WAYBILLS_PKEY = Indexes0.WAYBILLS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index WAYBILLPOSITION_PKEY = Internal.createIndex("waybillposition_pkey", Waybillposition.WAYBILLPOSITION, new OrderField[] { Waybillposition.WAYBILLPOSITION.NOMENCLATURE }, true);
        public static Index WAYBILLS_PKEY = Internal.createIndex("waybills_pkey", Waybills.WAYBILLS, new OrderField[] { Waybills.WAYBILLS.WAYBILLSID }, true);
    }
}
