/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Nomenclatures;
import db.tables.Waybillposition;
import db.tables.Waybills;
import db.tables.records.NomenclaturesRecord;
import db.tables.records.WaybillpositionRecord;
import db.tables.records.WaybillsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WaybillpositionRecord> WAYBILLPOSITION_PKEY = UniqueKeys0.WAYBILLPOSITION_PKEY;
    public static final UniqueKey<WaybillsRecord> WAYBILLS_PKEY = UniqueKeys0.WAYBILLS_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<NomenclaturesRecord, WaybillpositionRecord> NOMENCLATURES__NOMENCLATURES_NOMENCLATURE_FKEY = ForeignKeys0.NOMENCLATURES__NOMENCLATURES_NOMENCLATURE_FKEY;
    public static final ForeignKey<WaybillpositionRecord, WaybillsRecord> WAYBILLPOSITION__WAYBILLPOSITION_WAYBILLSID_FKEY = ForeignKeys0.WAYBILLPOSITION__WAYBILLPOSITION_WAYBILLSID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<WaybillpositionRecord> WAYBILLPOSITION_PKEY = Internal.createUniqueKey(Waybillposition.WAYBILLPOSITION, "waybillposition_pkey", Waybillposition.WAYBILLPOSITION.NOMENCLATURE);
        public static final UniqueKey<WaybillsRecord> WAYBILLS_PKEY = Internal.createUniqueKey(Waybills.WAYBILLS, "waybills_pkey", Waybills.WAYBILLS.WAYBILLSID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<NomenclaturesRecord, WaybillpositionRecord> NOMENCLATURES__NOMENCLATURES_NOMENCLATURE_FKEY = Internal.createForeignKey(db.Keys.WAYBILLPOSITION_PKEY, Nomenclatures.NOMENCLATURES, "nomenclatures__nomenclatures_nomenclature_fkey", Nomenclatures.NOMENCLATURES.NOMENCLATURE);
        public static final ForeignKey<WaybillpositionRecord, WaybillsRecord> WAYBILLPOSITION__WAYBILLPOSITION_WAYBILLSID_FKEY = Internal.createForeignKey(db.Keys.WAYBILLS_PKEY, Waybillposition.WAYBILLPOSITION, "waybillposition__waybillposition_waybillsid_fkey", Waybillposition.WAYBILLPOSITION.WAYBILLSID);
    }
}
