/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Authors;
import db.tables.Nomenclatures;
import db.tables.Organizations;
import db.tables.Waybillposition;
import db.tables.Waybills;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -817343053;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.AUTHORS</code>.
     */
    public final Authors AUTHORS = db.tables.Authors.AUTHORS;

    /**
     * The table <code>public.nomenclatures</code>.
     */
    public final Nomenclatures NOMENCLATURES = db.tables.Nomenclatures.NOMENCLATURES;

    /**
     * The table <code>public.organizations</code>.
     */
    public final Organizations ORGANIZATIONS = db.tables.Organizations.ORGANIZATIONS;

    /**
     * The table <code>public.waybillposition</code>.
     */
    public final Waybillposition WAYBILLPOSITION = db.tables.Waybillposition.WAYBILLPOSITION;

    /**
     * The table <code>public.waybills</code>.
     */
    public final Waybills WAYBILLS = db.tables.Waybills.WAYBILLS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Authors.AUTHORS,
            Nomenclatures.NOMENCLATURES,
            Organizations.ORGANIZATIONS,
            Waybillposition.WAYBILLPOSITION,
            Waybills.WAYBILLS);
    }
}
